### ISSUE TITLE
Organizar el repositorio

### ISSUE THREAD

**Issue by kalfaro-rydev** [lcampos-rydev/UVM_chapter_9_resultado#1]
Hola. Me gustaría si podrías organizar los archivos en directorios. Talvez similares al proyecto ejemplo

**Comment by kalfaro-rydev** [comment]
Tambien puedes actualizar un poco el readme, trate de _stylize_ el readme
Puedes utilizar este _cheatsheet_ [link](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

**Comment by lcampos-rydev** [comment]
Ya lo arregle bien todo
